convert:
#  - class: Integrated\Bundle\ContentBundle\Document\Content\Content
#    fields:
#      id: '"content-" ~ $.id.value()'
#      type_name: '$.contenttype.value()'
#      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Content"'
#      type_id: '$.id.value()'
#      pub_time: $.publishedAt.raw()
#      pub_created: $.createdAt.raw()
#      pub_edited: $.updatedAt.raw()
#    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\Article
    fields:
      id: '"article-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Article"'
      type_id: '$.id.value()'
      title: ~
      title_sort: '$.title.value()'
      subtitle: ~
      author: '$.authors[].person.concat(" ", ["@prefix", "@firstName", "@lastName"]).value()'
      source: ~
      intro: ~
      content: ~
      locale: ~
      pub_time: '$.publishedAt.raw()'
      pub_created: '$.createdAt.raw()'
      pub_edited: '$.updatedAt.raw()'
    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\File
    fields:
      id: '"file-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\File"'
      type_id: '$.id.value()'
      title: ~
      title_sort: '$.title.value()'
      description: ~
      intro: ~
      content: '$.description.value()'
      pub_time: '$.publishedAt.raw()'
      pub_created: '$.createdAt.raw()'
      pub_edited: '$.updatedAt.raw()'
    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\Image
    fields:
      id: '"image-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\File"'
      type_id: '$.id.value()'
      title: ~
      title_sort: '$.title.value()'
      description: ~
      intro: ~
      content: '$.description.value()'
      pub_time: $.publishedAt.raw()
      pub_created: $.createdAt.raw()
      pub_edited: $.updatedAt.raw()
      image_text: $.getWebPath().raw()
    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\Taxonomy
    fields:
      id: '"taxonomy-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Taxonomy"'
      type_id: '$.id.value()'
      title: ~
      title_sort: '$.title.value()'
      description: ~
      intro: ~
      content: '$.description.value()'
      pub_time: '$.publishedAt.raw()'
      pub_created: '$.createdAt.raw()'
      pub_edited: '$.updatedAt.raw()'
    id: id

#  - class: Integrated\Bundle\ContentBundle\Document\Content\Relation\Relation
#    fields:
#      id: '"relation-" ~ $.id.value()'
#      type_name: '$.contenttype.value()'
#      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Relation\\Relation"'
#      type_id: '$.id.value()'
#      title:  '$.name.value()'
#      description: ~
#      content: '$.description.value()'
#      phonenumber_text: '$.phonenumbers[].value()'
#      email_text: '$.email.value()'
#      address_text: '$.addresses[].concat(" ", ["@address1", "@address2", "@zipcode", "@city", "@state", "@country"]).value()'
#    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\Relation\Company
    fields:
      id: '"company-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Relation\\Company"'
      type_id: '$.id.value()'
      title: '$.name.value()'
      title_sort: '$.name.value()'
      description: ~
      intro: ~
      content: '$.description.value()'
      phonenumber_text: '$.phonenumbers[].value()'
      email_text: '$.email.value()'
      address_text: '$.addresses[].concat(" ", ["@address1", "@address2", "@zipcode", "@city", "@state", "@country"]).value()'
      pub_time: '$.publishedAt.raw()'
      pub_created: '$.createdAt.raw()'
      pub_edited: '$.updatedAt.raw()'
    id: id

  - class: Integrated\Bundle\ContentBundle\Document\Content\Relation\Person
    fields:
      id: '"person-" ~ $.id.value()'
      type_name: '$.contenttype.value()'
      type_class: '"Integrated\\Bundle\\ContentBundle\\Document\\Content\\Relation\\Person"'
      type_id: '$.id.value()'
      title: '$.concat(" ", ["@prefix", "@firstName", "@lastName"]).value()'
      title_sort: '$.concat(" ", ["@prefix", "@firstName", "@lastName"]).value()'
      description: ~
      intro: ~
      content: '$.description.value()'
      phonenumber_text: '$.phonenumbers[].value()'
      email_text: '$.email.value()'
      address_text: '$.addresses[].concat(" ", ["@address1", "@address2", "@zipcode", "@city", "@state", "@country"]).value()'
      pub_time: '$.publishedAt.raw()'
      pub_created: '$.createdAt.raw()'
      pub_edited: '$.updatedAt.raw()'
    id: id