convert:
  - class: Integrated\Bundle\ContentBundle\Document\Content\Article
    fields:
      id: '"article-" ~ document.id.value()'
      type_name: 'document.contenttype.value()'
      type_class: '"Integrated\Bundle\ContentBundle\Document\Content\Article"'
      type_id: 'id'
      title: ~
      content: ~
    id: id