install:
- curl -sS https://getcomposer.org/installer | php
before_script:
- php composer.phar update -n
script:
- vendor/bin/phpcs . --ignore=*/vendor/* --standard=PSR2 --extensions=php --runtime-set ignore_warnings_on_exit 1
- vendor/bin/phpunit -c phpunit.xml
