<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\UserBundle\Form\Type;

use Integrated\Bundle\UserBundle\Security\TwoFactor\Http\ContextInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Http\HttpUtils;

class AuthenticatorFormType extends AbstractType
{
    /**
     * @var HttpUtils
     */
    private $utils;

    public function __construct(HttpUtils $utils)
    {
        $this->utils = $utils;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('_auth_code', AuthenticatorType::class, [
            'label' => 'Enter the 6-digit authentication code generated by the Google Authenticator.',
            'user' => $options['context']->getUser(),
        ]);

        $builder->add('activate', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('method', 'post');

        $resolver->setNormalizer('action', function (Options $options, $value) {
            if ($value) {
                return $value;
            }

            return $this->utils->generateUri($options['context']->getRequest(), $options['context']->getConfig()->getCheckPath());
        });

        $resolver->setRequired('context');
        $resolver->setAllowedTypes('context', ContextInterface::class);
    }
}
