Integrated\Bundle\ChannelBundle\Model\Config:
  website-config-my-channel:
    name:     My channel
    adapter:  website
    channels: [my_channel]
    options:  '@website-config-my-channel-options'

Integrated\Bundle\ChannelBundle\Model\Options:
  website-config-my-channel-options:
    __construct:
      [theme: 'default']
